const CSVHeader = "File Path,Parse Error,Audit ID,Audit Date,Department,REI Style Number,Audit Level,Auditor,Season,Product Name,Audit Quality Level,Audit Type,Vendor,GA Product Number,Audit Lot Size,Production Status,Factory,Product Spec,Audit Sample Quantity,PO Number,Product Lifecycle,Audit Reject Quantity,Audit Accept Amount,Product Disposition Details,Critical Minor,Critical Major,Critical Critical,Critical RSI,Fabric Minor,Fabric Major,Fabric Critical,Fabric RSI,Hangtag Minor,Hangtag Major,Hangtag Critical,Hangtag RSI,Label Minor,Label Major,Label Critical,Label RSI,Measurement Minor,Measurement Major,Measurement Critical,Measurement RSI,Packaging Minor,Packaging Major,Packaging Critical,Packaging RSI,Packing Minor,Packing Major,Packing Critical,Packing RSI,Trim/Findings Minor,Trim/Findings Major,Trim/Findings Critical,Trim/Findings RSI,Vendor Spec Deviation Minor,Vendor Spec Deviation Major,Vendor Spec Deviation Critical,Vendor Spec Deviation RSI,Workmanship Minor,Workmanship Major,Workmanship Critical,Workmanship RSI,REI Spec Inaccuracy Minor,REI Spec Inaccuracy Major,REI Spec Inaccuracy Critical,REI Spec Inaccuracy RSI"

const nonconformityType = [
  "Critical",
  "Fabric",
  "Hangtag",
  "Label",
  "Measurement",
  "Packaging",
  "Packing",
  "Trim/Findings",
  "Vendor Spec Deviation",
  "Workmanship",
  "REI Spec Inaccuracy",
]

const sheetStructure = {
  "Audit Date-label": "B1",
  "Audit Date-value": "D1",
  "Auditor-label": "B2",
  "Auditor-value": "D2",
  "Audit Type-label": "B3",
  "Audit Type-value": "D3",
  "Production Status-label": "B4",
  "Production Status-value": "D4",
  "PO Number-label": "B5",
  "PO Number-value": "D5",
  "Department-label": "F1",
  "Department-value": "G1",
  "Product Name-label": "F2",
  "Product Name-value": "G2",
  "Vendor-label": "F3",
  "Vendor-value": "G3",
  "Factory-label": "F4",
  "Factory-value": "G4",
  "REI Style Number-label": "J1",
  "REI Style Number-value": "L1",
  "Season-label": "J2",
  "Season-value": "L2",
  "GA Product Number-label": "J3",
  "GA Product Number-value": "L3",
  "Product Spec-label": "J4",
  "Product Spec-value": "L4",
  "Product Lifecycle-label": "J5",
  "Product Lifecycle-value": "L5",
  "Audit Level-label": "M1",
  "Audit Level-value": "O1",
  "Audit Quality Level-label": "M2",
  "Audit Quality Level-value": "O2",
  "Audit Lot Size-label": "M3",
  "Audit Lot Size-value": "O3",
  "Audit Sample Quantity-label": "M4",
  "Audit Sample Quantity-value": "O4",
  "Audit Accept Amount-label": "M5",
  "Audit Accept Amount-value": "O5",
  "Non-conformity Type-label": "B8",
  "Total Minor Qty-label": "D8",
  "Total Major Qty-label": "F8",
  "Total Critical Qty-label": "H8",
  "Critical-label": "B9",
  "Critical Minor-value": "D9",
  "Critical Major-value": "F9",
  "Critical Critical-value": "H9",
  "Fabric-label": "B10",
  "Fabric Minor-value": "D10",
  "Fabric Major-value": "F10",
  "Fabric Critical-value": "H10",
  "Hangtag-label": "B11",
  "Hangtag Minor-value": "D11",
  "Hangtag Major-value": "F11",
  "Hangtag Critical-value": "H11",
  "Label-label": "B12",
  "Label Minor-value": "D12",
  "Label Major-value": "F12",
  "Label Critical-value": "H12",
  "Measurement-label": "B13",
  "Measurement Minor-value": "D13",
  "Measurement Major-value": "F13",
  "Measurement Critical-value": "H13",
  "Trim/Findings-label": "B14",
  "Trim/Findings Minor-value": "D14",
  "Trim/Findings Major-value": "F14",
  "Trim/Findings Critical-value": "H14",
  "Workmanship-label": "B15",
  "Workmanship Minor-value": "D15",
  "Workmanship Major-value": "F15",
  "Workmanship Critical-value": "H15",
  "Product Disposition Details-label": "B19",
  "Disposition Type-label": "B24",
}
const sheetName = "REI CFA Audit Result Form"

module.exports = {
  CSVHeader,
  nonconformityType,
  sheetStructure,
  sheetName,
}
